on:
  workflow_call:
    inputs:
      rust_components:
        required: false
        type: string

jobs:
  test-build:
    name: Build & Test
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-13
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: ${{ inputs.rust_components }}
      - name: Build
        run: cargo build --all-features
      - name: Test
        uses: bp3d-actions/cargo@main
        with:
          check-name: cargo test (${{ matrix.os }})
          command: test
          args: --all-features --no-fail-fast
          token: ${{ secrets.GITHUB_TOKEN }}
