on:
  workflow_call:

jobs:
  coverage:
    name: Coverage
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-13
          - windows-2019
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools
      - name: Install coverage tools
        run: cargo install cargo-llvm-cov
      - name: Build and test with coverage
        run: cargo llvm-cov --include-build-script --doctests --branch --all-features --workspace --html
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}
          path: target/llvm-cov/html
  deploy:
    name: Deploy
    needs: coverage
    if: github.ref == 'refs/heads/develop'
    permissions:
      pages: write
      id-token: write
      checks: write
      contents: read
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: coverage
      - name: Generate coverage summary
        run: |
            wget https://raw.githubusercontent.com/bp3d-actions/workflows/main/parse_coverage_report.py
            cd coverage
            python3 ../parse_coverage_report.py coverage-ubuntu-22.04 "Ubuntu 22.04" >> ../coverage.md
            python3 ../parse_coverage_report.py coverage-windows-2019 "Windows 2019" >> ../coverage.md
            python3 ../parse_coverage_report.py coverage-macos-13 "macOS 13" >> ../coverage.md
            cd ..
      - name: Upload web archive
        uses: actions/upload-pages-artifact@v3
        with:
          path: coverage
      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Upload coverage summary
        uses: bp3d-actions/checks-action@main
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            name: coverage
            conclusion: ${{ job.status }}
            output: |
                {"summary":"[<img src=\"${{ steps.deployment.outputs.page_url }}/coverage-macos-13.svg\">](${{ steps.deployment.outputs.page_url }}/coverage-macos-13)[<img src=\"${{ steps.deployment.outputs.page_url }}/coverage-ubuntu-20.04.svg\">](${{ steps.deployment.outputs.page_url }}/coverage-ubuntu-20.04)[<img src=\"${{ steps.deployment.outputs.page_url }}/coverage-windows-2019.svg\">](${{ steps.deployment.outputs.page_url }}/coverage-windows-2019)"}
            output_text_description_file: coverage.md
